#!/bin/bash

echo $(pwd)

# Set Variables
TEST_FILE="$1"
FULL_PATH=$(realpath "$1")
COMMAND=$(realpath "/home/vboxuser/Documents/fuzzing/mysort")		
TIMEOUT=2

# Print Vars
echo "Testing File: $FULL_PATH"
echo "Running Command: $COMMAND"
echo "Timeout Value: $TIMEOUT"

OUTPUT=$("$COMMAND" "$FULL_PATH" "$TIMEOUT" 2>&1)

# REMOVE COMMENT BELOW FOR DEBUGGING
# echo "$OUTPUT"

# Run the sort command and check for timeout
if echo "$OUTPUT" | grep -q "Error: timeout"; then
    echo "HANG"
    exit 0;
fi
echo "NO HANG"
exit 1;
